const products = [
  {
    id: 5,
    supplierId: 2,
    categoryId: 2,
    quantityPerUnit: "36 boxes",
    unitPrice: 21.35,
    unitsInStock: 0,
    unitsOnOrder: 0,
    reorderLevel: 0,
    discontinued: true,
    name: "Chef Anton's Gumbo Mix",
  },
  {
    id: 6,
    supplierId: 3,
    categoryId: 2,
    quantityPerUnit: "12 - 8 oz jars",
    unitPrice: 25,
    unitsInStock: 120,
    unitsOnOrder: 0,
    reorderLevel: 25,
    discontinued: false,
    name: "Grandma's Boysenberry Spread",
  },
  {
    id: 8,
    supplierId: 3,
    categoryId: 2,
    quantityPerUnit: "12 - 12 oz jars",
    unitPrice: 40,
    unitsInStock: 6,
    unitsOnOrder: 0,
    reorderLevel: 0,
    discontinued: false,
    name: "Northwoods Cranberry Sauce",
  },
  {
    id: 2,
    supplierId: 1,
    categoryId: 1,
    quantityPerUnit: "24 - 12 oz bottles",
    unitPrice: 19,
    unitsInStock: 17,
    unitsOnOrder: 40,
    reorderLevel: 25,
    discontinued: false,
    name: "Chang",
  },
  {
    id: 3,
    supplierId: 1,
    categoryId: 2,
    quantityPerUnit: "12 - 550 ml bottles",
    unitPrice: 10,
    unitsInStock: 13,
    unitsOnOrder: 70,
    reorderLevel: 25,
    discontinued: false,
    name: "Aniseed Syrup",
  },
  {
    id: 11,
    supplierId: 5,
    categoryId: 2,
    quantityPerUnit: "1 kg pkg.",
    unitPrice: 21,
    unitsInStock: 22,
    unitsOnOrder: 30,
    reorderLevel: 30,
    discontinued: false,
    name: "Queso Cabrales 2",
    supplier: {
      id: 5,
      companyName: "Cooperativa de Quesos 'Las Cabras'",
      contactName: "Antonio del Valle Saavedra",
      contactTitle: "Export Administrator",
      address: {
        street: "Calle del Rosal 4",
        city: "Oviedo",
        region: "Asturias",
        postalCode: 33007,
        country: "Spain",
        phone: "(98) 598 76 54",
      },
    },
    category: {
      id: 4,
      description: "Cheeses",
      name: "Dairy Products",
    },
  },
  {
    id: 15,
    supplierId: 6,
    categoryId: 2,
    quantityPerUnit: "24 - 250 ml bottles",
    unitPrice: 15.5,
    unitsInStock: 39,
    unitsOnOrder: 0,
    reorderLevel: 5,
    discontinued: false,
    name: "Genen Shouyu",
  },
  {
    id: 1,
    supplierId: 1,
    categoryId: 1,
    quantityPerUnit: "10 boxes x 20 bags",
    unitPrice: 18,
    unitsInStock: 39,
    unitsOnOrder: 0,
    reorderLevel: 10,
    discontinued: false,
    name: "Chai",
  },
  {
    id: 24,
    supplierId: 10,
    categoryId: 1,
    quantityPerUnit: "12 - 355 ml cans",
    unitPrice: 4.5,
    unitsInStock: 20,
    unitsOnOrder: 0,
    reorderLevel: 0,
    discontinued: true,
    name: "Guaraná Fantástica",
  },
  {
    id: 34,
    supplierId: 16,
    categoryId: 1,
    quantityPerUnit: "24 - 12 oz bottles",
    unitPrice: 14,
    unitsInStock: 111,
    unitsOnOrder: 0,
    reorderLevel: 15,
    discontinued: false,
    name: "Sasquatch Ale",
  },
  {
    id: 35,
    supplierId: 16,
    categoryId: 1,
    quantityPerUnit: "24 - 12 oz bottles",
    unitPrice: 18,
    unitsInStock: 20,
    unitsOnOrder: 0,
    reorderLevel: 15,
    discontinued: false,
    name: "Steeleye Stout",
  },
  {
    id: 38,
    supplierId: 18,
    categoryId: 1,
    quantityPerUnit: "12 - 75 cl bottles",
    unitPrice: 263.5,
    unitsInStock: 17,
    unitsOnOrder: 0,
    reorderLevel: 15,
    discontinued: false,
    name: "Côte de Blaye",
  },
  {
    id: 43,
    supplierId: 20,
    categoryId: 1,
    quantityPerUnit: "16 - 500 g tins",
    unitPrice: 46,
    unitsInStock: 17,
    unitsOnOrder: 10,
    reorderLevel: 25,
    discontinued: false,
    name: "Ipoh Coffee",
  },
  {
    id: 44,
    supplierId: 20,
    categoryId: 2,
    quantityPerUnit: "20 - 2 kg bags",
    unitPrice: 19.45,
    unitsInStock: 27,
    unitsOnOrder: 0,
    reorderLevel: 15,
    discontinued: false,
    name: "Gula Malacca",
  },
  {
    id: 39,
    supplierId: 18,
    categoryId: 1,
    quantityPerUnit: "750 cc per bottle",
    unitPrice: 18,
    unitsInStock: 69,
    unitsOnOrder: 0,
    reorderLevel: 5,
    discontinued: false,
    name: "Chartreuse verte",
  },
  {
    id: 61,
    supplierId: 29,
    categoryId: 2,
    quantityPerUnit: "24 - 500 ml bottles",
    unitPrice: 28.5,
    unitsInStock: 113,
    unitsOnOrder: 0,
    reorderLevel: 25,
    discontinued: false,
    name: "Sirop d'érable",
  },
  {
    id: 63,
    supplierId: 7,
    categoryId: 2,
    quantityPerUnit: "15 - 625 g jars",
    unitPrice: 43.9,
    unitsInStock: 24,
    unitsOnOrder: 0,
    reorderLevel: 5,
    discontinued: false,
    name: "Vegie-spread",
  },
  {
    id: 65,
    supplierId: 2,
    categoryId: 2,
    quantityPerUnit: "32 - 8 oz bottles",
    unitPrice: 21.05,
    unitsInStock: 76,
    unitsOnOrder: 0,
    reorderLevel: 0,
    discontinued: false,
    name: "Louisiana Fiery Hot Pepper Sauce",
  },
  {
    id: 66,
    supplierId: 2,
    categoryId: 2,
    quantityPerUnit: "24 - 8 oz jars",
    unitPrice: 17,
    unitsInStock: 4,
    unitsOnOrder: 100,
    reorderLevel: 20,
    discontinued: false,
    name: "Louisiana Hot Spiced Okra",
  },
  {
    id: 67,
    supplierId: 16,
    categoryId: 1,
    quantityPerUnit: "24 - 12 oz bottles",
    unitPrice: 14,
    unitsInStock: 52,
    unitsOnOrder: 0,
    reorderLevel: 10,
    discontinued: false,
    name: "Laughing Lumberjack Lager",
  },
  {
    id: 70,
    supplierId: 7,
    categoryId: 1,
    quantityPerUnit: "24 - 355 ml bottles",
    unitPrice: 15,
    unitsInStock: 15,
    unitsOnOrder: 10,
    reorderLevel: 30,
    discontinued: false,
    name: "Outback Lager",
  },
  {
    id: 75,
    supplierId: 12,
    categoryId: 1,
    quantityPerUnit: "24 - 0.5 l bottles",
    unitPrice: 7.75,
    unitsInStock: 125,
    unitsOnOrder: 0,
    reorderLevel: 25,
    discontinued: false,
    name: "Rhönbräu Klosterbier",
  },
  {
    id: 76,
    supplierId: 23,
    categoryId: 1,
    quantityPerUnit: "500 ml",
    unitPrice: 18,
    unitsInStock: 57,
    unitsOnOrder: 0,
    reorderLevel: 20,
    discontinued: false,
    name: "Lakkalikööri",
  },
  {
    id: 77,
    supplierId: 12,
    categoryId: 2,
    quantityPerUnit: "12 boxes",
    unitPrice: 13,
    unitsInStock: 32,
    unitsOnOrder: 0,
    reorderLevel: 15,
    discontinued: false,
    name: "Original Frankfurter grüne Soße",
  },
];

module.exports = {
  products,
};
